### ISSUE TITLE
Embedded Youtube Video http -> blocked by Chrome

### ISSUE THREAD

**Issue by Fizzzo42** [dogecoin/dogecoin.com#113]
Http content on a https page is blocked by Chrome and possibly other browsers (see https://www.howtogeek.com/443032/what-is-mixed-content-and-why-is-chrome-blocking-it/). When trying to load it, I get the following output in the console log:

Mixed Content: The page at 'https://dogecoin.com/' was loaded over HTTPS, but requested an insecure frame 'http://www.youtube.com/embed/_KVZmS_UO5I?enablejsapi=1&autoplay=1'. This request has been blocked; the content must be served over HTTPS.

The fix is pretty much a 1liner :):

<iframe style="border:none" width="400" height="225" src="**https://**www.youtube.com/embed/000al7ru3ms" allowfullscreen></iframe>

However I don't have access to create a branch + pull request. Not worked on many GitHub projects before, but if you hook me up I can create a small pull request.

Greetings
Özhan

**Comment by langerhans** [comment]
This has been fixed in the meantime, thanks!
