### ISSUE TITLE
> Why cant we just rewrite the entire site using react.js

### ISSUE THREAD

**Issue by freelancing-solutions** [dogecoin/dogecoin.com#126]
> Why cant we just rewrite the entire site using react.js

I was thinking the same thing. Let's collaborate.

_Originally posted by @arpitparmar5739 in https://github.com/dogecoin/dogecoin.com/pull/111#issuecomment-781102412_

**Comment by arpitparmar5739** [comment]
I know some more people who are interested in taking this responsibility. Just wanna know If this effort is worth it. @patricklodder, @rnicoll, and the team, what are your views?

**Comment by freelancing-solutions** [comment]
if we have to go this route we can easily get there by constantly making smaller changes until its done...
example
1.  First make sure the landing page works as a Single Page App.
2.  Integrate React through a Bundler
3. Refactor certain parts of the site into components
4. Use a Back-end framework such as NodeJS + Express , NextJS , Flask, or Fast-API  depending on what the majority of the people are capable of in this Repo
5.  Then Finally add more functionality such as Forums, Blog, Block Chain Explorer, and Stock Tickers

**Comment by guert** [comment]
@Bjzilberman

**Comment by freelancing-solutions** [comment]
can you tell me how you think we should start we can create a branch with our initial idea however still incorporating what is there already....and for now maybe even keeping the theme intact, and see if others approve or not ?

**Comment by rnicoll** [comment]
I know there's a couple of web devs already looking at a replacement, not sure who they are on GitHub to put you in contact though. Let me see if I can direct them here

**Comment by arpitparmar5739** [comment]
> can you tell me how you think we should start we can create a branch with our initial idea however still incorporating what is there already....and for now maybe even keeping the theme intact, and see if others approve or not ?

Hey man, waiting for @rnicoll to connect us to the people already working on similar task.

**Comment by leodavinci1** [comment]
I would love to work with React for this project :D.

**Comment by langerhans** [comment]
Can someone educate me about the benefits of this stuff for a strictly informational website? I personally don't see the need for anything that doesn't run on GitHub Pages like the current site. Very little hassle for a very good result. Personally things like a forum are a hard no from my side. We had that and it was barely used until it was overrun by spam bots and taken down. For the other stuff, question of benefits stands.

**Comment by arpitparmar5739** [comment]
> Can someone educate me about the benefits of this stuff for a strictly informational website? I personally don't see the need for anything that doesn't run on GitHub Pages like the current site. Very little hassle for a very good result. Personally things like a forum are a hard no from my side. We had that and it was barely used until it was overrun by spam bots and taken down. For the other stuff, question of benefits stands.

Please take a look at the websites of bitcoin and ethereum. The answer imo is very obvious.

PS: Please follow the links below for the websites,

https://bitcoin.org/en/
https://ethereum.org/en/eth/

**Comment by langerhans** [comment]
Both of these websites do not have any of the dynamic features proposed here. I don't see how that would answer my question. The choice of framework should be separate to the choice of content. What exactly is the scope of this issue? Is it just a brainstorming of the framework to use for a possible rewrite, or is it brainstorming things to put on the website? I think once this is established we can actually start looking into how to reach that goal, if we decide to go through with it.

**Comment by arpitparmar5739** [comment]
> Both of these websites do not have any of the dynamic features proposed here. I don't see how that would answer my question. The choice of framework should be separate to the choice of content. What exactly is the scope of this issue? Is it just a brainstorming of the framework to use for a possible rewrite, or is it brainstorming things to put on the website? I think once this is established we can actually start looking into how to reach that goal, if we decide to go through with it.

I agree with you that we should first decide the scope of the issue.

For me, the issue was created keeping the future of the website in mind. Website currently is just a single html page. We can plan something for the future of the website and at the same time brainstorm on what should we further add to the website to make it on par with the websites of other cryptos out there. Currently it's a way too basic IMO.

**Comment by langerhans** [comment]
I'm all for adding more good content to the website, don't get me wrong. But the choice of tech stack has little no influence on the scope of the website. So I ask everyone to keep that in mind when coming up with proposals for a complete rewrite :)

**Comment by arpitparmar5739** [comment]
The point is when you add that content the website grows larger. Using React for that would be a better choice is what I think and I assume @freelancing-solutions and @leodavinci1 had that same thing in his mind.

Please let us know what do you think. @langerhans

**Comment by langerhans** [comment]
Look I'm not hating on react or any other framework. I'm looking at this from a cost vs. value perspective. Given the requirements we have for a website the investment to reach the same goal with a framework that wasn't even built for static pages seems too large compared to the benefits it brings. And this isn't just an up front investment. It's also a matter of maintaining the page for years to come.

**Comment by arpitparmar5739** [comment]
Okay @langerhans.

**Comment by freelancing-solutions** [comment]
You can host a react site on any production server which you can host a static page for no additional costs

**Comment by freelancing-solutions** [comment]
The very cost needed to keep the present site up is exactly what is needed to keep a react site up, react sites are still single page web appications....

**Comment by langerhans** [comment]
I suggest reading this: https://en.wikipedia.org/wiki/Software_maintenance You will understand that "investment" is not a solely monetary driven term.

**Comment by freelancing-solutions** [comment]
Isnt that whats github and open source is suppose to be ...i mean no one is saying do it ...but just that people will most definetely do it ...

**Comment by arpitparmar5739** [comment]
> Look I'm not hating on react or any other framework. I'm looking at this from a cost vs. value perspective. Given the requirements we have for a website the investment to reach the same goal with a framework that wasn't even built for static pages seems too large compared to the benefits it brings. And this isn't just an up front investment. It's also a matter of maintaining the page for years to come.

@freelancing-solutions frankly bro that does not make sense to me. But @langerhans I still think that we should port the webpage. The reason being the webpage is so damn small right now that it does not matter which tech stack has been used to create it. It will remain maintainable (Also I know at least 5-6 people interested in porting right now). Now for me when doge goes to the moon I am speculating codebase of this small webpage will grow and at that time having things made up in React would be very useful. Please let us know your views on this. Thanks.

**Comment by patricklodder** [comment]
Hey everyone! My suggestion for today is you listen to this guy, he's famous: https://www.youtube.com/watch?v=WWVMXLSS1cA 

And then I suggest we all stop discussing that my framework is bigger/better than yours because that really doesn't help anyone.

Thank you, have a great day!
