### ISSUE TITLE
new responsive site

### ISSUE THREAD

**Issue by edswf1** [dogecoin/dogecoin.com#131]
i made a copy of the current site and ported it to a full responsive site:
[https://edswf1.github.io/dogecoin.com/](https://edswf1.github.io/dogecoin.com/)

i will add modals and tutorial tomorrow.
other todos are:
- resize images
- new mockup for dogecoin wallet
- seo
- and maybe some new text content?

**Comment by edswf1** [comment]
just updated the site:
- showing dogecoin price now
- added some effects
- redesigned download of wallets

TODOs:
- tutorial
- social links
- i18n integration
- seo
- resize images / new Mockups
- content of get started section (should exchanges be listed there?)

**Comment by davidbrouillette** [comment]
[Related issue 120 ](https://github.com/dogecoin/dogecoin.com/issues/120)

Could we consolidate the refactor effort?

**Comment by guert** [comment]
Beautiful


Sent from Yahoo Mail for iPhone


On Sunday, March 21, 2021, 11:50 AM, David Brouillette ***@***.***> wrote:




Related issue 120 

Could we consolidate the refactor effort?

**Comment by edswf1** [comment]
created a pull request after making the site fully functional.
tutorial is also live now: https://edswf1.github.io/dogecoin.com/

**Comment by carlosjunod** [comment]
what you mean with "resize images / new Mockups" can you elaborate?
