### ISSUE TITLE
Adblocker is blocking wallet download links

### ISSUE THREAD

**Issue by tuckbick** [dogecoin/dogecoin.com#139]
### Describe the issue

When I click any of the [download links](https://dogecoin.com/#wallets), my ad blocker ([uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)) blocks the request and a download prompt never appears. I assume this may occur with other ad blockers as well. Can anyone else reproduce this?

#### If so, please list the steps to reproduce below:
1. Load the page with uBlock chrome extension installed
2. Click any of the download links. Nothing should happen except a console error.
3. Disable uBlock and reload the page.
4. Click any of the download links. The download should work.

### Screenshots.
<img width="1075" alt="Screen Shot 2021-03-31 at 2 14 16 PM" src="https://user-images.githubusercontent.com/230995/113205365-73dc5280-922b-11eb-9c0f-35510705bb7f.png">

### Environment
- System: macOS
- Browser: Chrome 89.0.4389.90

**Comment by patricklodder** [comment]
Was found yesterday by our fabulous @langerhans and https://github.com/uBlockOrigin/uAssets/commit/10370b591f491b8429b6e406ca23bd53a841a8c2 should fix that.

**Comment by tuckbick** [comment]
Nice work! I updated my filter list and it works now.
