### ISSUE TITLE
iOS wallet app.

### ISSUE THREAD

**Issue by tjjosep** [dogecoin/dogecoin.com#158]
Is it possible to provide a reliable iOS based wallet app along with the android wallet app?

**Comment by langerhans** [comment]
Possible yes, and some iOS wallet apps exist. But none of the core devs are iOS devs as far as I'm aware so we'd have to defer to third party wallets for now. I'm going to close this issue as it's technically not related to the website. Maybe this is a good topic for /r/dogecoindev?
