### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by magneticat** [dogecoin/dogecoin.com#160]
I have started working on an Italian translation. It should be done soon. Is it OK? Can we add it to the website? 

I think an Italian version would make Dogecoin a bit more appealing to a lot of people that might have difficulties with English.

**Comment by cryptohakka** [comment]
I made issue #123 about Japanese translation but the time may not be ripe for localization as follows.
https://www.reddit.com/r/dogeducation/comments/ljg89s/about_localization/

**Comment by magneticat** [comment]
Hey cryptohakka, was not that post on reddit made before the release of the current version of the website?

I think the main thing, as we add languages, would be to change the bottom language selector in a dropdown.

**Comment by waddafunk** [comment]
Ciao @magneticat, let me know if i can help you and how with that italian translation.

**Comment by magneticat** [comment]
Ciao @waddafunk! I am adding a pull request soon, so you can review and do any changes you want to it!

**Comment by magneticat** [comment]
This should be complete, but I welcome revisions @waddafunk! I recommend you check the translation by browsing the actual webpage, as I figured out too late that a lot of text in the translations is not actually used in the websites anymore (opening a separate issue about this soon). Many phrases are not literal translation as they would have sounded horrible in Italian.

I fixed a couple more issues in this pull request with some missing language phrase locations.

**Comment by magneticat** [comment]
I did another re-read today and it seems fine so far. @waddafunk, if you have any input let us know so we can merge this and close the issue.

**Comment by waddafunk** [comment]
Sorry, been busy with my studies these days. I can review this tomorrow, if its not too late, otherwise feel free to proceed.

**Comment by waddafunk** [comment]
Ok so i reviewed your work and fixed some typos, cleaned some "eufonica" errors (for example i put "a una" instead of "ad una") and changed some phrases. [Made a branch with my corrections](https://github.com/waddafunk/dogecoin.com/tree/it-fixes) from your pull request. Check it out and let me know what you think, [this](https://github.com/waddafunk/dogecoin.com/commit/e635305085573458846db648321c7786a8c68bd0) is the commit you want to look at.

**Comment by magneticat** [comment]
@waddafunk looks perfect to me! Thanks for getting those typos and for making it sound more modern by removing the eufonica. I believe you can add it as a pull request to this issue and @patricklodder can then approve it. Great job,

Looks perfect to me now.

**Comment by waddafunk** [comment]
Thanks to you @magneticat for all the work you put in this! I created the pull request and linked it, cheers.

**Comment by magneticat** [comment]
Thanks to you ;) Yep, it took longer than it should have as half of the translation phrases are actually currently unused! But we will discuss that in future enhancements.

@patricklodder this looks great to me - many italians might need it ;)
