### ISSUE TITLE
Reduce the # of dogecoin production every year.

### ISSUE THREAD

**Issue by nitesh2382** [dogecoin/dogecoin.com#172]
### Feature Description
I think we need to control the production of Dogecoin every year.

### Use Case(s)
It can be valued more and useful for businesses. Businesses are accepting it more frequently now.

### Additional Context
1. Sports are accepting it.
2. online retailers are accepting it.
3. May be Billionaire can include as well like, Elon, Mark, etc..
To the Moon

**Comment by nickatnight** [comment]
I don't think this is relevant for dogecoin.com

Try [here](https://github.com/dogecoin/dogecoin) pal

**Comment by rnicoll** [comment]
Not part of the website and we've answered this endlessly before.
