### ISSUE TITLE
Add hindi language (code: hi ) translation 

### ISSUE THREAD

**Issue by vj-codes** [dogecoin/dogecoin.com#186]
### Feature Description
Add translation for the Hindi language as Hindi is the most spoken language in India and 
it is also the official language of the country along with English.

### Alternatives
No alternative

**Comment by vj-codes** [comment]
@langerhans @michilumin @patricklodder @rnicoll I would like to work on this once approved

**Comment by langerhans** [comment]
Someone added Hindi in #185 , it would be good if you could review the changes :)

**Comment by akhileshthite** [comment]
> Someone added Hindi in #185 , it would be good if you could review the changes :)

Yes @vj-codes, I've added screenshots in my PR #185 so you can review and suggest me any changes and corrections.
Thanks you :)

**Comment by langerhans** [comment]
Closing now that #185 is merged. Thanks!
