### ISSUE TITLE
Add marathi language (code: mr) translation 

### ISSUE THREAD

**Issue by vj-codes** [dogecoin/dogecoin.com#187]
### Feature Description
Add translation for the Marathi language as Marathi is the most spoken language in India 

### Alternatives
No alternative

**Comment by vj-codes** [comment]
@langerhans @michilumin @patricklodder @rnicoll I would like to work on this once approved

**Comment by langerhans** [comment]
Feel free to submit a pull request. Contributions like this are certainly welcome.
