### ISSUE TITLE
Word "find" written twice

### ISSUE THREAD

**Issue by Parasolio** [dogecoin/dogecoin.com#191]
### Describe the issue

There is word "find" written twice in the english main page. Not sure if this is intentional or not.

_"You can join team dogefolders, bring in your computing power, help to **find find** cures for diseases and receive some Doges for your efforts."_

### Can you reliably reproduce the issue?
yes

**Comment by vj-codes** [comment]
@Parasolio hey I found it too while translating and fixed it [here](https://github.com/dogecoin/dogecoin.com/pull/189/files#diff-e78dcb6d04b10991ca2424b63f71ca29953d6ba8803fa772bb8cc03ad593320f) yesterday 
Just letting you know so there aren't multiple fixes for the same :)
