### ISSUE TITLE
"Android Wallet" heading malformed

### ISSUE THREAD

**Issue by incognitojam** [dogecoin/dogecoin.com#197]
### Describe the issue
The "Android Wallet" text gets replaced by "dgc-android-wallet" after a few seconds.

#### If so, please list the steps to reproduce below:
1. Visit dogecoin.com

No actions required.

### Expected behaviour
It should say "Android Wallet".

### Actual behaviour
It says "Android Wallet" until (I suspect) i18n JavaScript loads and it gets changed to dgc-android-wallet.

### Screenshots.
![image](https://user-images.githubusercontent.com/4038174/117894675-caba5a80-b2b4-11eb-9019-753b97d41d45.png)

### Environment
- OS: Ubuntu 21.04
- Browser: Tested wtih Google Chrome 91.0.4472.38 beta (64-bit) and Firefox 88.0 (64-bit)
- System locale: en_GB.UTF-8

### Any extra information that might be useful in the debugging process.
There is no output in the console.

**Comment by langerhans** [comment]
Fixed in #199 , thanks!
