### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by gaetan-petit** [dogecoin/dogecoin.com#20]
Dogecoin.com definitely needs internationalisation to reach non english speaking shibes.
I would be please to help :)

@ummjackson : did you already think about it? Any preferences to achive this goal?

**Comment by shibyville** [comment]
I made a client side jQuery  translation  (Google translation is a joke, we need real shibes!) - Have a look here:

http://dogecoinmulti.send-a-wow.org/

If someone explain me Github i would be glad to upload it here.

**Comment by PowerLemons** [comment]
I'd be interested in collaborating with you on this @shibyville.
In its current state, I wish to do some changes to it. Not much, just some design changes.

To put it on Github just fork Dogecoin.com, then sync your files onto your forked repo.

**Comment by shibyville** [comment]
I will try it tomorrow. Git is new to me.

**Comment by gaetan-petit** [comment]
Check GitHub doc, it is awesome.

**Comment by gaetan-petit** [comment]
@shibyville I saw that you work on a i18n fork, is it ready for testing ?

**Comment by PowerLemons** [comment]
Closed as l89n has been added in PR #46.
