### ISSUE TITLE
How can I debug my translation file - zh-cn.json?

### ISSUE THREAD

**Issue by bobdos** [dogecoin/dogecoin.com#205]
I put a zh-cn.json under the folder i18n, then open the HTTP server to debug my translation, but no Chinese option on the dropdown list of Language. 

How can I config to see a Chinese option on the dropdown list?

![image](https://user-images.githubusercontent.com/195643/118063492-8c1fbf80-b3dc-11eb-86c2-4584d8927a63.png)

**Comment by vj-codes** [comment]
@bobdos hey your Chinese translated file should end `.json` and it will work

**Comment by hao6yu** [comment]
@bobdos add the new option to the language dropdown list in index.html and guide.html 
also need to update the js function in scripts.js to capture your new option as well

DM me if you need a hand

**Comment by bobdos** [comment]
> @bobdos add the new option to the language dropdown list in index.html and guide.html
> also need to update the js function in scripts.js to capture your new option as well
> 
> DM me if you need a hand

thanks I will have a try

**Comment by bobdos** [comment]
> @bobdos add the new option to the language dropdown list in index.html and guide.html
> also need to update the js function in scripts.js to capture your new option as well
> 
> DM me if you need a hand

all good, in progress right now. :)

![image](https://user-images.githubusercontent.com/195643/118207343-d15cf380-b4a7-11eb-899d-2938fe841a99.png)
