### ISSUE TITLE
Create a Portuguese Translation

### ISSUE THREAD

**Issue by xbeatzsec** [dogecoin/dogecoin.com#208]
### Started to translate to Portuguese
Editing the file for translate the page to Portuguese, this is the file -> https://github.com/xbeatzsec/dogecoin.com/blob/gh-pages/assets/i18n/pt.json

Best regards!

**Comment by nunocasco** [comment]
need help?

**Comment by xbeatzsec** [comment]
> need help?

Yeah we can do it together!

**Comment by nunocasco** [comment]
kardec#5691
add me at Discord. I'm a total newbie. But i guess i can translate, and you keep tracking if I don't accidentally delete or change something... (at least at discord we can speak pt so we can do this fast and well).
abraço
