### ISSUE TITLE
A way to keep mining a cleaner and greener Process as a selling point.

### ISSUE THREAD

**Issue by Landtd2015** [dogecoin/dogecoin.com#209]
Is it possible there is a way to add value to mining doge with exclusively green energy? like possibly a way to adjust the miner reward if they can prove their gear is powered by GE? This could be an extremely enticing sell point for the future. And also possibly a reward system to keep the mining as decentralized as possible, therefore keeping it in the hands of the people.

**Comment by freelancing-solutions** [comment]
There is no way to reliably detect the nature of electricity to determine if its green electricity or not, on the level of software.

With hardware it will still be unreliable but it can be done however will need extra hardware on top of the usual hardware the miner has. 

This however would be etremely difficult as it would require you to convince several manufactures of say solar panels, wind turbines and , etc to intergrate your hardware signalling requirements onto their equipment.

if all of this is not possible then it can be as simple as relying on hearsay...cause that what it would more or less be even with hardware and software solutions.

**Comment by freelancing-solutions** [comment]
the other thing is just understand that its cheaper to mine with green energy and then also assume that miners are not dumb.
this two assumptions can get you far. which makes you wonder what all the fuss is about..

**Comment by langerhans** [comment]
Yeah agree with the above points. It's a a good idea to encourage that, but there isn't a practical technical way to implement this. Also this is a bit unrelated to the website so I'll close this issue to keep the issue tracker focused.
