### ISSUE TITLE
Title on Support and guide pages missing space

### ISSUE THREAD

**Issue by wall03** [dogecoin/dogecoin.com#229]
![image](https://user-images.githubusercontent.com/65470133/118402335-7954f700-b637-11eb-9dcb-d096b033701f.png)
![image](https://user-images.githubusercontent.com/65470133/118402341-7fe36e80-b637-11eb-8acb-f31e2a757895.png)

there is a missing space on each title

**Comment by langerhans** [comment]
Solved by #215 , thanks!
