### ISSUE TITLE
Hacker issue

### ISSUE THREAD

**Issue by BigBlockDaddy** [dogecoin/dogecoin.com#231]
PLEASE  note 50k coins have been stolen from my encrypted wallet. I would  like to know how this is possible. I will explain my loss in detail so  there is NO confusion.
In 2014, I  acquired dogecoin for around 2 months through various transactions on  ebay and other means. Up until last week, that laptop sat on a shelf  with a dead battery and no internet connection whatsoever.
At  the beginning of this month, I downloaded a new 64 bit wallet, overwrote the wallet.dat file and allowed the wallet to update and  download the blockchain.
As it  finished this morning, I realized that on 5/6/2021, a -50,000  transaction had occurred WITHOUT any knowledge whatsoever on my part. My  old and new wallets show as being fully locked and no passphrases were  EVER given out, printed or ever looked at.
Looking  into more detail into this "transaction", it is CLEAR someone STOLE my  coins by tracking down an older transaction and redirecting it into  THEIR wallet. This is the address of the thief:    DGoBxd82tyyhPBbd1qcmAdqJVsWyANnNsQ
By the looks of the wallet's activities, this one account has been doing this for a few weeks now:
https://dogechain.info/address/DGoBxd82tyyhPBbd1qcmAdqJVsWyANnNsQ
How  can something like this happen? I can prove the 50k transaction I  originally made because the addresses are clearly in the blockchain.
Here is the specific transaction of my STOLEN coins: https://dogechain.info/tx/759bb9e9ea8cc7d13053fa5376555150cd899f850d07124853d67d9717349857
The address the coins were taken from is a random RECEIVING address I gave the guy who I bought the coins from.. How is this possible?
Now, unless I'm a complete idiot and messed up severely - This is a very serious matter and a very serious breach of security. I would love some feedback on this from someone smarter than me.
Should a NEW doge wallet be updated (blockchain) BEFORE copying an old wallet.dat file over? I have so many questions now. Biggest one is - Can I get MY coins back??
PLEASE HELP I'm freaking out here...

### Describe the issue
Tell us about the issue

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the website, screenshots can be added to this issue via drag & drop.

### Environment
- OS:
- Browser:

### Any extra information that might be useful in the debugging process.
This is normally the contents of the [developer console](https://javascript.info/devtools). Raw text or a link to a [pastebin](https://pastebin.com/) type site are preferred.

**Comment by NeilShah2026** [comment]
Hey, this is the GitHub Repo for the Dogecoin.com, not dogechain, as we have no affiliation with them. Have you tried sending them a message?

**Comment by langerhans** [comment]
To make sure the coins actually left the wallet run Dogecoin core with the -rescan command line option once. But please post such question on e.g. /r/dogeducation as this is the issue tracker for the dogecoin.com website and this this topic is completely off-topic.
