### ISSUE TITLE
Online wallets

### ISSUE THREAD

**Issue by leofidus** [dogecoin/dogecoin.com#24]
dogechain.info, dogeapi.com and moolah.io are listed as recommended online wallets, with the note "These online wallets are not owned or maintained by Dogecoin or the Dogecoin Foundation. While we are satisfied they are trustworthy, reliable services - please use at your own risk."

The key phrase here is "While we are satisfied they are trustworthy". dogechain.info details why its wallet is secure and is in fact a trustless wallet (i.e. you don't have to trust them if you can check the javascript source code). For the other two wallets, I wasn't able to find any information about there security procedures. So the natural thing to ask is: Why are they listed as trustworthy? What exactly does that word mean in this context? Is it just trust that they won't run with our funds?

(and sorry, no personal offence meant, just asking questions which I think should be asked)

**Comment by langerhans** [comment]
The wording has been changed for now. Leaving this open for further improvements where needed.
