### ISSUE TITLE
Add an essential function for the getting started of dogecoin.com

### ISSUE THREAD

**Issue by MacTheZazou** [dogecoin/dogecoin.com#26]
Hi,

I have an idea to make the getting started realy powerful!

Let the actual shibe create a unique link with doge on (max 5000 doges) and they just have to share this link with new shibe who will be completly guided with the getting started and at the end, they put her freshly new dogecoin address and they receive the amount who was on the link!

Sry for bad english, I'm french o/

**Comment by PowerLemons** [comment]
Unfortunately even though I would like to try this, something like this would require PHP/Python/Ruby and SQLite. GitHub Pages only allows HTML, CSS, and JS - static pages with no backend. I also don't know PHP/Python/Ruby myself.

Closing. Thanks for the suggestion though!
