### ISSUE TITLE
License for dogecoin.com

### ISSUE THREAD

**Issue by dhpollack** [dogecoin/dogecoin.com#28]
What is the license for dogecoin.com?  I wanted to throw it into duolingo.com to translate the site into different languages, but can only do so if the site has a non-commercial license.

**Comment by felixvd** [comment]
I have started a crowdsourced translation effort here: http://www.getlocalization.com/dogecoin/

It is possible to link master files to the Github so they're updated automatically in the future. There are no license restrictions on that website, either

I'll try to organize in /r/dogecointranslation. Feel free to post there :)
