### ISSUE TITLE
add HolyTransaction.com to the list of wallets

### ISSUE THREAD

**Issue by nixoid** [dogecoin/dogecoin.com#4]
Please add HolyTransaction to the wallet list.

HolyTransaction it’s a hosted wallet designed for nontechnical users. Users can send and receive cryptocurrency from your mobile browser or over social networks. It's a online web wallet that offers a simple and instant exchange among top cryptocurrencies. 
You can read about how it works in our FAQ.

With just an email, users can send and receive cryptocurrency from anyone, instantly.
Mobile support, Instant Exchange, Multi-currency, Social Tipping, Cold-Storage Security, Google Authenticator 2FA, QR Codes, transaction history, exchange history, Open API and more. It's looks great on tablets and smartphones.

Let us know if you have any questions.

**Comment by dhpollack** [comment]
@PowerLemons you can close this issue since Holy Transactions has already been added.

**Comment by PowerLemons** [comment]
Closed as it has been added.
