### ISSUE TITLE
dogedir.com suspended

### ISSUE THREAD

**Issue by jflaloux** [dogecoin/dogecoin.com#43]
I don't know for how long the issue is going on.
dogedir.com leads to : http://dogedir.com/cgi-sys/suspendedpage.cgi
If it's final it should be remover from the Store tab

**Comment by PowerLemons** [comment]
Dogedir.com has been removed. Thanks for opening this issue.

**Comment by josephfusco** [comment]
Dogedir.com is back up. Sorry about that. I am actually working on a dogedir 3.0 at the moment.

**Comment by PowerLemons** [comment]
@josephfusco No problem, Dogedir has already been added back in. Thanks for maintaining the website!
