### ISSUE TITLE
Add Celery under 'Online Wallets' and 'Get Dogecoin'

### ISSUE THREAD

**Issue by dthakur** [dogecoin/dogecoin.com#56]
We're a hosted wallet and buying service.

[Celery](https://www.gocelery.com)
[Coindesk coverage](http://www.coindesk.com/celery-launches-consumer-friendly-bitcoin-dogecoin-buying-service/)
[Transparency and dogecoin holdings](https://www.gocelery.com/#transparency)

I previously opened a PR, but it was ignored for a very long time.

**Comment by PowerLemons** [comment]
Celery has replaced Vault of Satoshi, since VoS has closed down. Thank you for bringing your site to our attention.
