### ISSUE TITLE
Place a link to the Android wallet on the page

### ISSUE THREAD

**Issue by langerhans** [dogecoin/dogecoin.com#63]
Regarding this post: https://www.reddit.com/r/dogecoin/comments/2k61o1/chinese_shibes_need_help_we_cant_download_the/ 

It would be nice to have a direct link to the Android wallet download somewhere for the shibes that cannot or don't want to use use Google Play.

Here is the website for it: https://langerhans.github.io/dogecoin-wallet-new/

**Comment by PowerLemons** [comment]
This has been implemented. Thanks for the suggestion!
