### ISSUE TITLE
Link doges.org as community

### ISSUE THREAD

**Issue by Dogedealer** [dogecoin/dogecoin.com#65]
Hi doges.org used to be linked on dogecoin.com as the original forum and community. Would you guys add it back as I asked Jackson Palmer about this and he said to submit a pull request and it will be added. I request the admin and mods of dogecoin.com to add doges.org in community section of the site so new people know about it. doges.org already has over 13000 members and all info regarding dogecoin and anytime someone needs a problem solved regarding dogecoin they post a thread and problem is solved. Thanks in advance for your cooperation fellow shibes.

**Comment by PowerLemons** [comment]
@ummjackson, can you verify this?

**Comment by Dogedealer** [comment]
![image](https://cloud.githubusercontent.com/assets/9728390/5036991/74cc706e-6b84-11e4-9dfe-9376dc7c9600.png)

**Comment by Dogedealer** [comment]
Im still waiting for you guys to add it? Whats happening mods?

**Comment by PowerLemons** [comment]
Did he say that your forum _should_ be added? The website already has the [official forums](https://discuss.dogecoin.com/), and your forums (in my opinion) look unfriendly to new shibes - which is what the website is targeted at.

**Comment by Dogedealer** [comment]
How can you claim its unfriendly from any angle please explain? It launched same day as dogecoin and is and has always been the Official Dogecoin forum since then. It needs to be linked back on the site as it used to be there till April I remember. I ll contact Jackson again and see what he has to say about your allegations about the forum.

**Comment by PowerLemons** [comment]
Don't take this the wrong way, it's great that you launched the first Dogecoin forum. But your site has gambling ads, questionable threads like [this](http://doges.org/such-profit/btcpro-programs-to-help-you-captitalize-on-the-rise-of-bitcoins/), and trades like [this](http://doges.org/fetching-coins/facebooktwitterinstayoutube-booster-service-$21000-likesharefollowsub/) and [this](http://doges.org/fetching-coins/%28dogecoinbitcoinany-other-coin%29-faucet-script/). I don't think newcomers would have a good image of the coin if the website supported it.

And unless I'm mistaken, the Discuss Dogecoin forum is the only official forum of Dogecoin.

**Comment by Dogedealer** [comment]
First of all Whats wrong with discussing dogecoin and related crypto on a dogeocin forum? Have you seen bitcoin talk forum anytime ? Ads are all dogecoin related and only of products and services with dogecoin in mind .  

The spam you linked to happens every now and then and is deleted daily but since its a high traffic forum with over 13000 members it takes time for the mods to take care of.  If you have a personal grudge against me please be clear about it dont make things up about the forum. The forum your talking about discuss dogecoin forum is as good as dead since there is no one there I wouldn't even call that a forum looks more like a announcement board for developers. 

Keep in mind by not linking doges.org your harming the dogecoin community and taking us all down who are here for dogecoin and supporting it rather than judging and complaining about each other. Dogecoin has already lost a lot of value because of bad behavior of various developers with new shibes.

The point is all Im asking is the forum was linked till april then the new site didn't. I would it to be linked back and let the new shibes decide whether they like it or not? Who knows Dogecoin will gain more value as we guide newbies all day long on our forum and give them free dogecoins daily to keep the network running.

**Comment by Dogedealer** [comment]
Some questionable links from discuss dogecoin 
https://discuss.dogecoin.com/discussion/474/bitteaser-banners-teasers-network-for-all-cryptocurrency-businesses
https://discuss.dogecoin.com/discussion/471/of-beats-and-freestyles-day-1

https://discuss.dogecoin.com/discussion/472/startjoin-fundraiser-campaign-for-cryptocurrency-book

**Comment by ummjackson** [comment]
@Dogedealer @PowerLemons After reviewing doges.org in more detail, I can't condone it being added to the official website. It's full of gambling ads (the entire section above the fold is banners) and has questionable / scammy content. 

The Dogecoin Foundation are currently looking into other options for official, moderated forums. Closing this thread.

**Comment by Dogedealer** [comment]
Well all banner ads are of dogecoin casinos and Games. If you don't like dogecoin related games and casinos I guess you should release a policy stating that dogecoin should not be used on casinos and games or such. Then Id be happy to remove the banners. 

None of the banners are scammy or questionable please point out which game or casino you found out to be scammy with proof and Id be happy to blacklist it right away and not put up there banners for life. 

By not linking us to the main site your making a huge mistake as we as 13000 members feel cheated by you the developers as we believed in dogecoin and invested huge amounts into it and now that its 1/10 of the value as it was in February were still supporting and trying to get more people from crypto community involved into dogecoin. And all you do is cut us off? How many banners does reddit have you still link them as community is that not questionable? 

Id like to know the right reason why you wont link it?

**Comment by Dogedealer** [comment]
If your not comfortable as adding it as official forum just ad it in communities as a normal forum then? Or in other section?

**Comment by ummjackson** [comment]
The Doges.org forums were listed on the website until it was over-run by scammers and became very heavy on the advertising side. The owner of the forums "drexme" was also exposed to be a scammer who'd run off with a lot of people's NXT in the past... it all had a shady feeling to it. 

Judging from the Doges.org footer reporting it looks as if there are only around 100 visits a day to the forums... I'm not saying that discuss.dogecoin.com is any better, but I wouldn't class either as a high traffic forum. Coupled with the shady history + multitude of advertisements on the website, I'm just not inclined to add it as a link on Dogecoin.com. 

Seeing a wall of banner ads isn't a good first time experience for new users, and I'm concerned that your persistence in trying to get the site added is driven predominantly by you wanting to raise advertising revenue on those banners.

If the forum cleans up all of the above and starts seeing the community traffic that the /r/dogecoin subreddit does, then we can revisit this in the future.

**Comment by Dogedealer** [comment]
100 visitors lol. Id like to show you the traffic stats of each day to prove you wrong heres a screenshot from first week of march http://imgur.com/4XjHMQr if you like its a lot more than that. The footer says over 100 members were online at the sametime if you can read it correct.

Drexme I dont know him all I know is he used to run the forum the first 3-4 months and after that I took over so what he did or was has nothing to do with the forum.  I already make enough with the banner ads I dont need a higher revenue and trust be no revenue will grow by linking if it did discuss dogecoin forum would be having a lot more members and action. 

If you would like to add just do it to the main site if not its cool I dont need your advice or tips regarding my forum its running pretty well already. If you knew so much discuss dogecoin wouldn't of been such a flop and empty forum. Thanks and Goodluck shows what kind of developers dogecoin is run by.

**Comment by Dogedealer** [comment]
Had you guys planned better dogecoin wouldnt of fallen in value from 2.5$ Per K to 0.23$ Per K.

**Comment by ummjackson** [comment]
To clarify, I'm not the lead developer or chief maintainer of the website. Dogecoin is run by the community, so if you think there is some merit in adding the forum to the website then get their support in doing so. To date, you're the only person who's suggested adding it and you're the owner (+ ad revenue maker) of the forum. 

Regarding traffic, how about you share the October 2014 numbers rather than March 2014 to give a sense of current data?

As for the price, if that's what you care about when it comes to Dogecoin you're kind of missing the point.

**Comment by Dogedealer** [comment]
Id Love to share the august-october 2014 numbers thats not a problem for me. But why should I waste my energy if your not adding a simple site as a link to the main dogecoin site? Why so much debate and this and that rather than just linking it is it so hard for you? If you link it  Ill share the stats otherwise I wont.

If you think dogecoins price is not important then I wonder what was going on in your head when launching a cryptocurrency. When you launch a currency you launch it for the value not for fun. Games are launched for fun if you get the point. You do understand people buy dogecoins with real and hard earned money right and not for fun? If you want dogecoin to not be taken seriously or valued I suggest you do a big announcement on reddit about it Id like to see the community reaction.

**Comment by PowerLemons** [comment]
Your forum will not be added to the website. It has been decided. You may revisit this with us if your forum complies to what Jackson said, but for now it will not be added.
