### ISSUE TITLE
Getting started guide for contributing to the site?

### ISSUE THREAD

**Issue by vmu9999** [dogecoin/dogecoin.com#67]
I pulled the git repository, but I'm having issues simply getting all the assets to display properly.

**Comment by PowerLemons** [comment]
Are you using a web development platform like WAMP to display the webpage? Simply opening the HTML file isn't enough.

**Comment by vmu9999** [comment]
That's what I mean, power. How can I get started? There isn't any indication on the readme about needing WAMP.

**Comment by PowerLemons** [comment]
Sorry, I thought you meant the Getting Started guide on the website. If you want to display the website locally and edit it, here's how to do it.

[Install WAMP](http://www.wampserver.com/en/). Once you finish installing it, put the website files in the /www directory of the WAMP directory. By default, the location of the WAMP directory is C:/wamp. Put "localhost" into the address of your browser to display the site.

You can edit the site in the /www directory. If you have anymore questions, let me know.

**Comment by dhpollack** [comment]
@cantbecool if you want to go with a complete cloud solution, you can use c9.io.  I created a super quick picture tutorial.  Note that I directly cloned the dogecoin.com repo, but you'd probably want to clone the repo to your github account, connect your github account, and then connect that to c9.io.

http://imgur.com/a/4EJC2

**Comment by vmu9999** [comment]
thanks @dhpollack I'm going to look into that solution. I'm going to have some time around the holidays, so hopefully I can contribute.

**Comment by ghost** [comment]
@cantbecool If you use Windows, use <a href="www.apachefriends.org">XAMPP</a>.
I had many problems with WAMP.... ._.

**Comment by greensn0w** [comment]
@PowerLemons @cantbecool This issue should be closed because the PR is merged
