### ISSUE TITLE
Can replace jQuery.js off Google references??

### ISSUE THREAD

**Issue by R32** [dogecoin/dogecoin.com#69]
Because in China, can't open Google

**Comment by orawalters** [comment]
Maybe a compromise? We could use Jquery off the official CDN (`code.jquery.org`) or write in a backup script like this:

```
if (typeof jQuery == 'undefined') {
document.write(unescape("%3Cscript src='/js/jquery-1.11.0.min.js' type='text/javascript'%3E%3C/script%3E"));
     }
```

**Comment by PowerLemons** [comment]
Changed the CDN for jQuery from Google to the Official CDN. Thank you for letting us know about this!
