### ISSUE TITLE
Enable the Wiki to host the "Getting started"-guides

### ISSUE THREAD

**Issue by ghost** [dogecoin/dogecoin.com#70]
Please enable the Wiki to host the "Getting started"-guides.

I already created the guides for Linux and Windows: https://github.com/greensn0w/dogecoin.com/tree/webdev-getting-started

References #67

**Comment by dhpollack** [comment]
agreed

**Comment by PowerLemons** [comment]
Can you make a pull request? I'll merge it once you do. Thank you for your contribution to Dogecoin.com!

**Comment by dhpollack** [comment]
@PowerLemons creating a wiki is not something that can be done with a pull request.  You need to enable it in the settings of the project.

https://help.github.com/articles/disabling-wikis/

It's like that, except exactly the opposite.

**Comment by ghost** [comment]
@PowerLemons: https://help.github.com/articles/about-github-wikis/

**Comment by ghost** [comment]
I close this issue, because the guides are already merged :grimacing:
