### ISSUE TITLE
www.dogecoin.com subdomain doesn't work

### ISSUE THREAD

**Issue by peoplma** [dogecoin/dogecoin.com#94]
http://dogecoin.com works, but http://www.dogecoin.com doesn't work.  I am not sure who the DNS provider for dogecoin.com is or how their CNAME records work, but the CNAME record should be altered to point www.dogecoin.com to dogecoin.com.

Thanks to /u/beardog108 for pointing this out.

**Comment by patricklodder** [comment]
This has been fixed, works for me now.
