### ISSUE TITLE
Change Android Wallet "Get it On Google Play" image src

### ISSUE THREAD

**Issue by ghost** [dogecoin/dogecoin.com#98]
The src "https://developer.android.com/images/brand/en_generic_rgb_wo_60.png" in the image for the Android download window 404's, and therefore does not display. 

I've had this issue with my apps, it seems Google changed the way the URL is structured.

You can create the URL [here](https://play.google.com/intl/en_us/badges/).

**Comment by patricklodder** [comment]
thx for reporting. putting it on my todo
